/**
 * Seed New Cairo Kids Areas
 * Adds popular kids areas that are missing from the existing database.
 * Skips any place whose name_en already exists.
 *
 * Usage: npx dotenv-cli -e .env.local -- npx tsx scripts/seed-new-places.ts
 */

import mongoose from "mongoose";
import Place from "../src/lib/models/Place";

// Category IDs: 1=play, 2=cinema, 3=gardens/parks, 4=arts/education, 5=animals/farms, 6=restaurants

const NEW_PLACES = [
  // ─── أماكن لعب ومرح (Play & Fun) ───
  {
    name_ar: "أفريكانو بارك",
    name_en: "Africano Park",
    description_short: "حديقة حيوانات وسفاري مفتوحة على طريق الإسماعيلية. تجربة سفاري أفريقية حقيقية للأطفال والعائلات",
    area: "Cairo-Alex Desert Road",
    city: "Cairo",
    address: "Km 58 Cairo-Ismailia Desert Road",
    location: { lat: 30.2955, lon: 31.6803 },
    min_price: 200, max_price: 450, price_range_id: 3,
    min_age: 2, max_age: 16,
    avg_duration_hours: 4,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: false,
    phone: "+20 100 100 8868",
    category_ids: [5, 3],
    image_url: "",
  },
  {
    name_ar: "جنة مول - منطقة الألعاب",
    name_en: "Genena Mall Kids Area",
    description_short: "منطقة ألعاب للأطفال داخل جنة مول في مدينة نصر",
    area: "Nasr City",
    city: "Cairo",
    address: "Genena Mall, Nasr City",
    location: { lat: 30.0561, lon: 31.3456 },
    min_price: 50, max_price: 150, price_range_id: 1,
    min_age: 2, max_age: 12,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "ماجيك جالاكسي",
    name_en: "Magic Galaxy",
    description_short: "مركز ترفيهي كبير للأطفال مع ألعاب إلكترونية ومنطقة لعب",
    area: "6 Oct./ Sheikh Zayed",
    city: "Cairo",
    address: "Arkan Plaza, Sheikh Zayed",
    location: { lat: 30.0178, lon: 31.0097 },
    min_price: 100, max_price: 300, price_range_id: 2,
    min_age: 3, max_age: 14,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "جولي لاند",
    name_en: "Jolly Land",
    description_short: "مدينة ألعاب ترفيهية للأطفال في سيتي ستارز",
    area: "Heliopolis",
    city: "Cairo",
    address: "City Stars Mall, Heliopolis",
    location: { lat: 30.0733, lon: 31.3467 },
    min_price: 80, max_price: 200, price_range_id: 2,
    min_age: 2, max_age: 12,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "فن بلانيت",
    name_en: "Fun Planet",
    description_short: "مركز ترفيه للعائلات مع ألعاب متنوعة للأطفال",
    area: "New Cairo",
    city: "Cairo",
    address: "Downtown Mall, New Cairo",
    location: { lat: 30.0283, lon: 31.4478 },
    min_price: 80, max_price: 200, price_range_id: 2,
    min_age: 2, max_age: 14,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "ميجا فن",
    name_en: "Mega Fun",
    description_short: "مدينة ترفيهية كبيرة للأطفال مع ترامبولين وألعاب متنوعة",
    area: "6 Oct./ Sheikh Zayed",
    city: "Cairo",
    address: "Mall of Arabia, 6th of October",
    location: { lat: 29.9728, lon: 30.9945 },
    min_price: 100, max_price: 250, price_range_id: 2,
    min_age: 3, max_age: 14,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },

  // ─── نوادي رياضية (Sports Clubs with kids facilities) ───
  {
    name_ar: "نادي الجزيرة الرياضي",
    name_en: "Gezira Sporting Club",
    description_short: "نادي رياضي عريق في الزمالك مع مناطق لعب وأنشطة أطفال ومسابح",
    area: "Zamalek",
    city: "Cairo",
    address: "Gezira Island, Zamalek",
    location: { lat: 30.0437, lon: 31.2243 },
    min_price: 0, max_price: 0, price_range_id: 1,
    min_age: 0, max_age: 18,
    avg_duration_hours: 4,
    is_free: false,
    indoor_outdoor: "mixed" as const,
    booking_required: false,
    phone: "+20 2 2735 6000",
    category_ids: [1, 3],
    image_url: "",
  },
  {
    name_ar: "نادي هليوبوليس الرياضي",
    name_en: "Heliopolis Sporting Club",
    description_short: "نادي رياضي في مصر الجديدة مع مرافق أطفال ومسابح وملاعب",
    area: "Heliopolis",
    city: "Cairo",
    address: "Heliopolis, Cairo",
    location: { lat: 30.0911, lon: 31.3389 },
    min_price: 0, max_price: 0, price_range_id: 1,
    min_age: 0, max_age: 18,
    avg_duration_hours: 4,
    is_free: false,
    indoor_outdoor: "mixed" as const,
    booking_required: false,
    phone: "+20 2 2417 8400",
    category_ids: [1, 3],
    image_url: "",
  },
  {
    name_ar: "نادي الصيد المصري",
    name_en: "Shooting Club",
    description_short: "نادي رياضي واجتماعي في الدقي مع حدائق ومناطق لعب أطفال",
    area: "Mohandiseen/Dokki",
    city: "Cairo",
    address: "Dokki, Giza",
    location: { lat: 30.0380, lon: 31.2030 },
    min_price: 0, max_price: 0, price_range_id: 1,
    min_age: 0, max_age: 18,
    avg_duration_hours: 4,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: false,
    phone: "+20 2 3337 3656",
    category_ids: [1, 3],
    image_url: "",
  },
  {
    name_ar: "نادي المعادي الرياضي",
    name_en: "Maadi Sporting Club",
    description_short: "نادي رياضي في المعادي مع أنشطة أطفال ومسابح وملاعب",
    area: "Maadi",
    city: "Cairo",
    address: "Maadi, Cairo",
    location: { lat: 29.9608, lon: 31.2572 },
    min_price: 0, max_price: 0, price_range_id: 1,
    min_age: 0, max_age: 18,
    avg_duration_hours: 4,
    is_free: false,
    indoor_outdoor: "mixed" as const,
    booking_required: false,
    phone: "",
    category_ids: [1, 3],
    image_url: "",
  },
  {
    name_ar: "نادي وادي دجلة",
    name_en: "Wadi Degla Club",
    description_short: "نادي رياضي اجتماعي مع مرافق أطفال وأنشطة رياضية متنوعة",
    area: "New Cairo",
    city: "Cairo",
    address: "New Cairo, Fifth Settlement",
    location: { lat: 30.0182, lon: 31.4401 },
    min_price: 0, max_price: 0, price_range_id: 1,
    min_age: 0, max_age: 18,
    avg_duration_hours: 4,
    is_free: false,
    indoor_outdoor: "mixed" as const,
    booking_required: false,
    phone: "",
    category_ids: [1, 3],
    image_url: "",
  },
  {
    name_ar: "نادي الأهلي - فرع الشيخ زايد",
    name_en: "Al Ahly Club Sheikh Zayed",
    description_short: "فرع نادي الأهلي في الشيخ زايد مع أنشطة رياضية وترفيهية للأطفال",
    area: "6 Oct./ Sheikh Zayed",
    city: "Cairo",
    address: "Sheikh Zayed City",
    location: { lat: 30.0314, lon: 31.0014 },
    min_price: 0, max_price: 0, price_range_id: 1,
    min_age: 0, max_age: 18,
    avg_duration_hours: 4,
    is_free: false,
    indoor_outdoor: "mixed" as const,
    booking_required: false,
    phone: "",
    category_ids: [1, 3],
    image_url: "",
  },
  {
    name_ar: "نادي الشمس",
    name_en: "Nadi El Shams",
    description_short: "نادي الشمس الرياضي مع مسابح وأنشطة أطفال في مصر الجديدة",
    area: "Heliopolis",
    city: "Cairo",
    address: "Ain Shams, Cairo",
    location: { lat: 30.1172, lon: 31.3233 },
    min_price: 0, max_price: 0, price_range_id: 1,
    min_age: 0, max_age: 18,
    avg_duration_hours: 4,
    is_free: false,
    indoor_outdoor: "mixed" as const,
    booking_required: false,
    phone: "",
    category_ids: [1, 3],
    image_url: "",
  },

  // ─── متاحف ومعالم (Museums & Landmarks) ───
  {
    name_ar: "المتحف المصري الكبير",
    name_en: "Grand Egyptian Museum (GEM)",
    description_short: "أكبر متحف أثري في العالم بجوار الأهرامات. تجربة تعليمية مذهلة للأطفال",
    area: "Giza",
    city: "Cairo",
    address: "Cairo-Alexandria Desert Road, Giza",
    location: { lat: 29.9953, lon: 31.1172 },
    min_price: 200, max_price: 500, price_range_id: 3,
    min_age: 3, max_age: 18,
    avg_duration_hours: 4,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: true,
    phone: "",
    category_ids: [4],
    image_url: "",
  },
  {
    name_ar: "المتحف المصري بالتحرير",
    name_en: "Egyptian Museum Tahrir",
    description_short: "المتحف المصري الشهير في ميدان التحرير. رحلة تعليمية في تاريخ مصر القديم",
    area: "Garden City/Downtown",
    city: "Cairo",
    address: "Tahrir Square, Downtown Cairo",
    location: { lat: 30.0478, lon: 31.2336 },
    min_price: 30, max_price: 200, price_range_id: 2,
    min_age: 4, max_age: 18,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "+20 2 2578 2452",
    category_ids: [4],
    image_url: "",
  },
  {
    name_ar: "متحف الطفل بهيئة الاستعلامات",
    name_en: "Children's Civilization & Creativity Center",
    description_short: "متحف تفاعلي للأطفال في مصر الجديدة مع أنشطة علمية وفنية",
    area: "Heliopolis",
    city: "Cairo",
    address: "34 Abu Bakr El Siddiq, Heliopolis",
    location: { lat: 30.0874, lon: 31.3425 },
    min_price: 10, max_price: 50, price_range_id: 1,
    min_age: 3, max_age: 15,
    avg_duration_hours: 2,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "+20 2 2638 0823",
    category_ids: [4],
    image_url: "",
  },

  // ─── حدائق ومتنزهات (Parks & Gardens) ───
  {
    name_ar: "حديقة الميريلاند",
    name_en: "Merryland Garden",
    description_short: "حديقة عامة جميلة في مصر الجديدة مع مناطق لعب أطفال",
    area: "Heliopolis",
    city: "Cairo",
    address: "Merryland, Heliopolis",
    location: { lat: 30.0908, lon: 31.3278 },
    min_price: 5, max_price: 20, price_range_id: 1,
    min_age: 0, max_age: 16,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [3],
    image_url: "",
  },
  {
    name_ar: "حديقة الفسطاط",
    name_en: "Fustat Garden",
    description_short: "حديقة كبيرة في مصر القديمة مناسبة للعائلات والأطفال",
    area: "Old Cairo",
    city: "Cairo",
    address: "Fustat, Old Cairo",
    location: { lat: 30.0058, lon: 31.2333 },
    min_price: 5, max_price: 10, price_range_id: 1,
    min_age: 0, max_age: 18,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [3],
    image_url: "",
  },
  {
    name_ar: "حديقة الحرية",
    name_en: "Freedom Park",
    description_short: "حديقة عامة مع مناطق لعب للأطفال ومساحات خضراء",
    area: "Nasr City",
    city: "Cairo",
    address: "Nasr City, Cairo",
    location: { lat: 30.0543, lon: 31.3592 },
    min_price: 5, max_price: 10, price_range_id: 1,
    min_age: 0, max_age: 16,
    avg_duration_hours: 2,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [3],
    image_url: "",
  },
  {
    name_ar: "حديقة الطفل",
    name_en: "Children's Garden Maadi",
    description_short: "حديقة مخصصة للأطفال في المعادي مع ألعاب ومساحات آمنة",
    area: "Maadi",
    city: "Cairo",
    address: "Maadi, Cairo",
    location: { lat: 29.9626, lon: 31.2591 },
    min_price: 5, max_price: 15, price_range_id: 1,
    min_age: 0, max_age: 12,
    avg_duration_hours: 2,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [3, 1],
    image_url: "",
  },

  // ─── مزارع وحيوانات (Farms & Animals) ───
  {
    name_ar: "مزرعة الهناء",
    name_en: "Al Hanaa Farm",
    description_short: "مزرعة تعليمية للأطفال مع حيوانات أليفة وأنشطة زراعية",
    area: "6 Oct./ Sheikh Zayed",
    city: "Cairo",
    address: "6th of October, Giza",
    location: { lat: 29.9800, lon: 31.0200 },
    min_price: 100, max_price: 250, price_range_id: 2,
    min_age: 2, max_age: 14,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: true,
    phone: "",
    category_ids: [5],
    image_url: "",
  },
  {
    name_ar: "مزرعة ديجا فو",
    name_en: "Deja Vu Farm",
    description_short: "مزرعة ترفيهية مع ركوب خيل وأنشطة حيوانية للأطفال",
    area: "6 Oct./ Sheikh Zayed",
    city: "Cairo",
    address: "Abu Rawash, 6th of October",
    location: { lat: 30.0667, lon: 31.0833 },
    min_price: 100, max_price: 300, price_range_id: 2,
    min_age: 3, max_age: 16,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: true,
    phone: "",
    category_ids: [5],
    image_url: "",
  },

  // ─── فنون وتعليم (Arts & Education) ───
  {
    name_ar: "بيت السناري",
    name_en: "Beit El Sennari",
    description_short: "بيت أثري تاريخي ينظم ورش عمل فنية وتعليمية للأطفال",
    area: "Old Cairo",
    city: "Cairo",
    address: "Haret Monge, Sayyida Zeinab",
    location: { lat: 30.0284, lon: 31.2516 },
    min_price: 0, max_price: 50, price_range_id: 1,
    min_age: 5, max_age: 16,
    avg_duration_hours: 2,
    is_free: true,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [4],
    image_url: "",
  },
  {
    name_ar: "مركز الإبداع الفني",
    name_en: "Art Creativity Center Zamalek",
    description_short: "مركز فني في الزمالك يقدم ورش رسم ونحت وفنون للأطفال",
    area: "Zamalek",
    city: "Cairo",
    address: "Zamalek, Cairo",
    location: { lat: 30.0617, lon: 31.2239 },
    min_price: 100, max_price: 300, price_range_id: 2,
    min_age: 4, max_age: 16,
    avg_duration_hours: 2,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: true,
    phone: "",
    category_ids: [4],
    image_url: "",
  },
  {
    name_ar: "مكتبة مصر العامة",
    name_en: "Egypt Public Library Zamalek",
    description_short: "مكتبة عامة مع قسم أطفال وأنشطة قراءة وورش تعليمية",
    area: "Zamalek",
    city: "Cairo",
    address: "26th of July Street, Zamalek",
    location: { lat: 30.0606, lon: 31.2247 },
    min_price: 0, max_price: 0, price_range_id: 1,
    min_age: 3, max_age: 16,
    avg_duration_hours: 2,
    is_free: true,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [4],
    image_url: "",
  },

  // ─── مطاعم مناسبة للأطفال (Kid-friendly Restaurants) ───
  {
    name_ar: "لاكي بارك",
    name_en: "Lucky Park",
    description_short: "مطعم ومنطقة ألعاب للأطفال في مصر الجديدة",
    area: "Heliopolis",
    city: "Cairo",
    address: "Heliopolis, Cairo",
    location: { lat: 30.0867, lon: 31.3439 },
    min_price: 100, max_price: 300, price_range_id: 2,
    min_age: 2, max_age: 12,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "mixed" as const,
    booking_required: false,
    phone: "",
    category_ids: [6, 1],
    image_url: "",
  },

  // ─── سينما وعروض (Cinema & Shows) ───
  {
    name_ar: "آي ماكس مول مصر",
    name_en: "IMAX Mall of Egypt",
    description_short: "سينما آي ماكس في مول مصر مع أفلام ثلاثية الأبعاد مناسبة للأطفال",
    area: "6 Oct./ Sheikh Zayed",
    city: "Cairo",
    address: "Mall of Egypt, 6th of October",
    location: { lat: 29.9722, lon: 30.9953 },
    min_price: 150, max_price: 350, price_range_id: 2,
    min_age: 4, max_age: 18,
    avg_duration_hours: 2,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: true,
    phone: "",
    category_ids: [2],
    image_url: "",
  },
  {
    name_ar: "سينما رينيسانس",
    name_en: "Renaissance Cinema",
    description_short: "سينما عائلية مع صالات مريحة وأفلام أطفال",
    area: "New Cairo",
    city: "Cairo",
    address: "Cairo Festival City Mall, New Cairo",
    location: { lat: 30.0300, lon: 31.4062 },
    min_price: 100, max_price: 300, price_range_id: 2,
    min_age: 3, max_age: 18,
    avg_duration_hours: 2,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [2],
    image_url: "",
  },

  // ─── أماكن ترفيهية إضافية (More Entertainment) ───
  {
    name_ar: "بورتو كايرو مول - منطقة الأطفال",
    name_en: "Porto Cairo Mall Kids Zone",
    description_short: "مناطق لعب متنوعة للأطفال داخل بورتو كايرو مول",
    area: "New Cairo",
    city: "Cairo",
    address: "Porto Cairo Mall, Fifth Settlement",
    location: { lat: 30.0192, lon: 31.4295 },
    min_price: 50, max_price: 200, price_range_id: 2,
    min_age: 2, max_age: 14,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "كايرو فيستيفال سيتي مول - ألعاب الأطفال",
    name_en: "Cairo Festival City Kids Area",
    description_short: "مناطق ترفيه وألعاب أطفال داخل كايرو فيستيفال سيتي مول",
    area: "New Cairo",
    city: "Cairo",
    address: "Cairo Festival City Mall, New Cairo",
    location: { lat: 30.0303, lon: 31.4065 },
    min_price: 50, max_price: 200, price_range_id: 2,
    min_age: 2, max_age: 14,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "صن سيتي مول - منطقة الأطفال",
    name_en: "Sun City Mall Kids Zone",
    description_short: "منطقة ألعاب للأطفال في صن سيتي مول مصر الجديدة",
    area: "Heliopolis",
    city: "Cairo",
    address: "Sun City Mall, Heliopolis",
    location: { lat: 30.0789, lon: 31.3500 },
    min_price: 50, max_price: 150, price_range_id: 1,
    min_age: 2, max_age: 12,
    avg_duration_hours: 2,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "مول مصر - منطقة الأطفال",
    name_en: "Mall of Egypt Kids Area",
    description_short: "مناطق ترفيه وألعاب متنوعة للأطفال في مول مصر",
    area: "6 Oct./ Sheikh Zayed",
    city: "Cairo",
    address: "Mall of Egypt, 6th of October",
    location: { lat: 29.9728, lon: 30.9945 },
    min_price: 50, max_price: 200, price_range_id: 2,
    min_age: 2, max_age: 14,
    avg_duration_hours: 3,
    is_free: false,
    indoor_outdoor: "indoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "أوبن اير مول - منطقة الأطفال",
    name_en: "Open Air Mall Kids Area",
    description_short: "مناطق لعب مفتوحة للأطفال في أوبن اير مول المعادي",
    area: "Maadi",
    city: "Cairo",
    address: "Open Air Mall, Maadi",
    location: { lat: 29.9550, lon: 31.2673 },
    min_price: 50, max_price: 150, price_range_id: 1,
    min_age: 2, max_age: 12,
    avg_duration_hours: 2,
    is_free: false,
    indoor_outdoor: "mixed" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "كريزي ووتر",
    name_en: "Crazy Water",
    description_short: "مدينة ألعاب مائية للأطفال والعائلات",
    area: "6 Oct./ Sheikh Zayed",
    city: "Cairo",
    address: "6th of October, Giza",
    location: { lat: 29.9600, lon: 31.0100 },
    min_price: 150, max_price: 400, price_range_id: 3,
    min_age: 3, max_age: 16,
    avg_duration_hours: 5,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
  {
    name_ar: "أكوا بارك - العبور",
    name_en: "Aqua Park Obour",
    description_short: "مدينة ألعاب مائية كبيرة في مدينة العبور",
    area: "Al Shorouk/ Madinaty/Obour",
    city: "Cairo",
    address: "Obour City, Cairo",
    location: { lat: 30.2323, lon: 31.4714 },
    min_price: 100, max_price: 300, price_range_id: 2,
    min_age: 3, max_age: 16,
    avg_duration_hours: 5,
    is_free: false,
    indoor_outdoor: "outdoor" as const,
    booking_required: false,
    phone: "",
    category_ids: [1],
    image_url: "",
  },
];

async function main() {
  const MONGODB_URI = process.env.MONGODB_URI;
  if (!MONGODB_URI) {
    console.error("❌ MONGODB_URI not set");
    process.exit(1);
  }

  console.log("🔌 Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI);
  console.log("✅ Connected");

  // Get current max order
  const maxOrderDoc = await Place.findOne({}).sort({ order: -1 }).lean();
  let nextOrder = (maxOrderDoc?.order ?? 0) + 1;

  let added = 0;
  let skipped = 0;

  for (const place of NEW_PLACES) {
    // Check for duplicate by name_en
    const existing = await Place.findOne({ name_en: place.name_en });
    if (existing) {
      console.log("⏭️  Skipped (exists): " + place.name_en);
      skipped++;
      continue;
    }

    await Place.create({
      ...place,
      website_url: "",
      external_source: "Manual",
      external_detail_url: "",
      facebook_url: "",
      instagram_url: "",
      last_price_update: new Date(),
      offer_text: "",
      offer_active: false,
      offer_expiry: null,
      active: true,
      order: nextOrder++,
    });

    console.log("✅ Added: " + place.name_ar + " (" + place.name_en + ")");
    added++;
  }

  // Final stats
  const total = await Place.countDocuments({});
  const cairoTotal = await Place.countDocuments({ city: "Cairo" });

  console.log("\n📊 Results:");
  console.log("   Added: " + added);
  console.log("   Skipped: " + skipped);
  console.log("   Total places in DB: " + total);
  console.log("   Total Cairo places: " + cairoTotal);

  // Area breakdown for Cairo
  const areaBreakdown = await Place.aggregate([
    { $match: { city: "Cairo", active: true } },
    { $group: { _id: "$area", count: { $sum: 1 } } },
    { $sort: { count: -1 } },
  ]);
  console.log("\n🏙️  Cairo areas:");
  for (const { _id, count } of areaBreakdown) {
    console.log("   " + _id + ": " + count);
  }

  await mongoose.disconnect();
  console.log("\n👋 Done");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
